//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppForWebSvc.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Movie", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Movie : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short VideoCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MovieTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MovieTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RatingField;
        
        private System.Nullable<float> RentalPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProducerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirectorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MediaField;
        
        private System.Nullable<short> TotalStockField;
        
        private System.Nullable<short> NumberRentedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short VideoCode {
            get {
                return this.VideoCodeField;
            }
            set {
                if ((this.VideoCodeField.Equals(value) != true)) {
                    this.VideoCodeField = value;
                    this.RaisePropertyChanged("VideoCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MovieTitle {
            get {
                return this.MovieTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.MovieTitleField, value) != true)) {
                    this.MovieTitleField = value;
                    this.RaisePropertyChanged("MovieTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MovieType {
            get {
                return this.MovieTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MovieTypeField, value) != true)) {
                    this.MovieTypeField = value;
                    this.RaisePropertyChanged("MovieType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((object.ReferenceEquals(this.RatingField, value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<float> RentalPrice {
            get {
                return this.RentalPriceField;
            }
            set {
                if ((this.RentalPriceField.Equals(value) != true)) {
                    this.RentalPriceField = value;
                    this.RaisePropertyChanged("RentalPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ProducerID {
            get {
                return this.ProducerIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ProducerIDField, value) != true)) {
                    this.ProducerIDField = value;
                    this.RaisePropertyChanged("ProducerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Director {
            get {
                return this.DirectorField;
            }
            set {
                if ((object.ReferenceEquals(this.DirectorField, value) != true)) {
                    this.DirectorField = value;
                    this.RaisePropertyChanged("Director");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Media {
            get {
                return this.MediaField;
            }
            set {
                if ((object.ReferenceEquals(this.MediaField, value) != true)) {
                    this.MediaField = value;
                    this.RaisePropertyChanged("Media");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<short> TotalStock {
            get {
                return this.TotalStockField;
            }
            set {
                if ((this.TotalStockField.Equals(value) != true)) {
                    this.TotalStockField = value;
                    this.RaisePropertyChanged("TotalStock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<short> NumberRented {
            get {
                return this.NumberRentedField;
            }
            set {
                if ((this.NumberRentedField.Equals(value) != true)) {
                    this.NumberRentedField = value;
                    this.RaisePropertyChanged("NumberRented");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetMovieIdsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMovieIds", ReplyAction="*")]
        ConsoleAppForWebSvc.ServiceReference1.GetMovieIdsResponse GetMovieIds(ConsoleAppForWebSvc.ServiceReference1.GetMovieIdsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMovieIds", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleAppForWebSvc.ServiceReference1.GetMovieIdsResponse> GetMovieIdsAsync(ConsoleAppForWebSvc.ServiceReference1.GetMovieIdsRequest request);
        
        // CODEGEN: Generating message contract since element name GetMovieResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMovie", ReplyAction="*")]
        ConsoleAppForWebSvc.ServiceReference1.GetMovieResponse GetMovie(ConsoleAppForWebSvc.ServiceReference1.GetMovieRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMovie", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleAppForWebSvc.ServiceReference1.GetMovieResponse> GetMovieAsync(ConsoleAppForWebSvc.ServiceReference1.GetMovieRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMovieIdsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMovieIds", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleAppForWebSvc.ServiceReference1.GetMovieIdsRequestBody Body;
        
        public GetMovieIdsRequest() {
        }
        
        public GetMovieIdsRequest(ConsoleAppForWebSvc.ServiceReference1.GetMovieIdsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetMovieIdsRequestBody {
        
        public GetMovieIdsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMovieIdsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMovieIdsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleAppForWebSvc.ServiceReference1.GetMovieIdsResponseBody Body;
        
        public GetMovieIdsResponse() {
        }
        
        public GetMovieIdsResponse(ConsoleAppForWebSvc.ServiceReference1.GetMovieIdsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMovieIdsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleAppForWebSvc.ServiceReference1.ArrayOfInt GetMovieIdsResult;
        
        public GetMovieIdsResponseBody() {
        }
        
        public GetMovieIdsResponseBody(ConsoleAppForWebSvc.ServiceReference1.ArrayOfInt GetMovieIdsResult) {
            this.GetMovieIdsResult = GetMovieIdsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMovieRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMovie", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleAppForWebSvc.ServiceReference1.GetMovieRequestBody Body;
        
        public GetMovieRequest() {
        }
        
        public GetMovieRequest(ConsoleAppForWebSvc.ServiceReference1.GetMovieRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMovieRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetMovieRequestBody() {
        }
        
        public GetMovieRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMovieResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMovieResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleAppForWebSvc.ServiceReference1.GetMovieResponseBody Body;
        
        public GetMovieResponse() {
        }
        
        public GetMovieResponse(ConsoleAppForWebSvc.ServiceReference1.GetMovieResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMovieResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleAppForWebSvc.ServiceReference1.Movie GetMovieResult;
        
        public GetMovieResponseBody() {
        }
        
        public GetMovieResponseBody(ConsoleAppForWebSvc.ServiceReference1.Movie GetMovieResult) {
            this.GetMovieResult = GetMovieResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : ConsoleAppForWebSvc.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<ConsoleAppForWebSvc.ServiceReference1.WebServiceSoap>, ConsoleAppForWebSvc.ServiceReference1.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleAppForWebSvc.ServiceReference1.GetMovieIdsResponse ConsoleAppForWebSvc.ServiceReference1.WebServiceSoap.GetMovieIds(ConsoleAppForWebSvc.ServiceReference1.GetMovieIdsRequest request) {
            return base.Channel.GetMovieIds(request);
        }
        
        public ConsoleAppForWebSvc.ServiceReference1.ArrayOfInt GetMovieIds() {
            ConsoleAppForWebSvc.ServiceReference1.GetMovieIdsRequest inValue = new ConsoleAppForWebSvc.ServiceReference1.GetMovieIdsRequest();
            inValue.Body = new ConsoleAppForWebSvc.ServiceReference1.GetMovieIdsRequestBody();
            ConsoleAppForWebSvc.ServiceReference1.GetMovieIdsResponse retVal = ((ConsoleAppForWebSvc.ServiceReference1.WebServiceSoap)(this)).GetMovieIds(inValue);
            return retVal.Body.GetMovieIdsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleAppForWebSvc.ServiceReference1.GetMovieIdsResponse> ConsoleAppForWebSvc.ServiceReference1.WebServiceSoap.GetMovieIdsAsync(ConsoleAppForWebSvc.ServiceReference1.GetMovieIdsRequest request) {
            return base.Channel.GetMovieIdsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleAppForWebSvc.ServiceReference1.GetMovieIdsResponse> GetMovieIdsAsync() {
            ConsoleAppForWebSvc.ServiceReference1.GetMovieIdsRequest inValue = new ConsoleAppForWebSvc.ServiceReference1.GetMovieIdsRequest();
            inValue.Body = new ConsoleAppForWebSvc.ServiceReference1.GetMovieIdsRequestBody();
            return ((ConsoleAppForWebSvc.ServiceReference1.WebServiceSoap)(this)).GetMovieIdsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleAppForWebSvc.ServiceReference1.GetMovieResponse ConsoleAppForWebSvc.ServiceReference1.WebServiceSoap.GetMovie(ConsoleAppForWebSvc.ServiceReference1.GetMovieRequest request) {
            return base.Channel.GetMovie(request);
        }
        
        public ConsoleAppForWebSvc.ServiceReference1.Movie GetMovie(int id) {
            ConsoleAppForWebSvc.ServiceReference1.GetMovieRequest inValue = new ConsoleAppForWebSvc.ServiceReference1.GetMovieRequest();
            inValue.Body = new ConsoleAppForWebSvc.ServiceReference1.GetMovieRequestBody();
            inValue.Body.id = id;
            ConsoleAppForWebSvc.ServiceReference1.GetMovieResponse retVal = ((ConsoleAppForWebSvc.ServiceReference1.WebServiceSoap)(this)).GetMovie(inValue);
            return retVal.Body.GetMovieResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleAppForWebSvc.ServiceReference1.GetMovieResponse> ConsoleAppForWebSvc.ServiceReference1.WebServiceSoap.GetMovieAsync(ConsoleAppForWebSvc.ServiceReference1.GetMovieRequest request) {
            return base.Channel.GetMovieAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleAppForWebSvc.ServiceReference1.GetMovieResponse> GetMovieAsync(int id) {
            ConsoleAppForWebSvc.ServiceReference1.GetMovieRequest inValue = new ConsoleAppForWebSvc.ServiceReference1.GetMovieRequest();
            inValue.Body = new ConsoleAppForWebSvc.ServiceReference1.GetMovieRequestBody();
            inValue.Body.id = id;
            return ((ConsoleAppForWebSvc.ServiceReference1.WebServiceSoap)(this)).GetMovieAsync(inValue);
        }
    }
}
